dari-web/src/main/java/managedBeans/OffersBean.java
package managedBeans;

import java.io.Serializable;
import java.util.ArrayList;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.model.SelectItem;

import Entities.Requests;
import Enumerates.Governorateenum;
import Enumerates.Type;
import Enumerates.Typech;
import Services.*;

@SessionScoped
@ManagedBean(name="offersbean", eager = true)
public class OffersBean implements Serializable {
	
	private int Budget;
	private int Area;
    private Typech typechval;
    private Type typeval;
    private Governorateenum Governorateenumval;
	private ArrayList<SelectItem> delegations	=new ArrayList<SelectItem>();
    private String delegationval;
    private ArrayList<Requests> requestslist;
    private Requests request;

    
	@EJB
	OffersServices ds = new OffersServices();
    
	@ManagedProperty(value="#{loginBean}") 
    private LoginBean loginBean;
    
    
    
    
    
    
    
	 public String scan() {
	    	String navigateTo = "null";

		navigateTo = "/offers/Index?faces-redirect=true";

		return navigateTo;
	 }
	
    
    
    
	public int getBudget() {
		return Budget;
	}
	public void setBudget(int budget) {
		Budget = budget;
	}
	public int getArea() {
		return Area;
	}
	public void setArea(int area) {
		Area = area;
	}
	public Typech getTypechval() {
		return typechval;
	}
	public void setTypechval(Typech typechval) {
		this.typechval = typechval;
	}
	public Type getTypeval() {
		return typeval;
	}
	public void setTypeval(Type typeval) {
		this.typeval = typeval;
	}
	public Governorateenum getGovernorateenumval() {
		return Governorateenumval;
	}
	public void setGovernorateenumval(Governorateenum governorateenumval) {
		Governorateenumval = governorateenumval;
	}
	public ArrayList<SelectItem> getDelegations() {
		if (Governorateenumval.BEN.equals(getGovernorateenumval()))
		{
			delegations.clear();
		delegations.add(new SelectItem("2222,Megrine,MG"));
		delegations.add(new SelectItem("5555,Rades,RD"));	
		setDelegations(delegations);

			return delegations;

			}
		if (Governorateenumval.BIZ.equals(getGovernorateenumval()))
		{	
			delegations.clear();

		delegations.add(new SelectItem("1111,zarzoun,za"));
		delegations.add(new SelectItem("1202,B Ville,BV"));
setDelegations(delegations);
			return delegations;
		}
		return null;
			}
	public void setDelegations(ArrayList<SelectItem> delegations) {
		this.delegations = delegations;
	}
	public String getDelegationval() {
		return delegationval;
	}
	public void setDelegationval(String delegationval) {
		this.delegationval = delegationval;
	}




	public ArrayList<Requests> getRequestslist() {
		requestslist=ds.bestoffers(loginBean.getRole(), loginBean.getUserid(), Budget, Area, typechval, typeval, Governorateenumval, delegationval);
		return requestslist;	}




	public void setRequestslist(ArrayList<Requests> requestslist) {
		this.requestslist = requestslist;
	}




	public Requests getRequest() {
		return request;
	}




	public void setRequest(Requests request) {
		this.request = request;
	}




	public LoginBean getLoginBean() {
		return loginBean;
	}




	public void setLoginBean(LoginBean loginBean) {
		this.loginBean = loginBean;
	}
    
    
    
    
    
    
    
    
    
    
    
    

	
	
	
	
	

}

dari-web/src/main/java/managedBeans/TypechBean.java
package managedBeans;

import java.io.Serializable;

import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;

import Enumerates.*;

@ManagedBean(name= "enumbean")
@ApplicationScoped
public class TypechBean implements Serializable {
	private static final long serialVersionUID= 1L;
	public Typech[] getTypech() {
		return Typech.values();
	}
	public Type[] getType() {
		return Type.values();
	}
	public Governorateenum[] getGovernorateenum() {
			
			return Governorateenum.values();
			
	}
	

}

dari-web/src/main/webapp/offers/Create.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core" 	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"        xmlns:p="http://primefaces.org/ui"
	  xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"	template="/template/template.xhtml">
	<ui:param name="page_name" value="Connexion" />
	<ui:define name="content">
	    <div class="container">
        <div class="row">
            <div class="col-lg-8 offset-lg-2">
                <div class="pd-hero-text">

                    <h2>WELCOME</h2>
                   
            <h:form>
			<h5>	<h:outputText	value=" #{loginBean.login}" /> </h5>
										<h5>	<h:outputText	value=" #{loginBean.role}" /> </h5>
				
				<h:commandButton value="Logout" action="#{loginBean.doLogout()}" class="btn btn-primary btn-sm" />
			</h:form>

                </div>
            </div>
        </div>

    </div>
	

    <h:graphicImage library="img" name="product-content-bg.jpg" />
    

<h:form id="content" >
    <br></br><br></br><br></br><center><h4>Property Info</h4></center><br></br><br></br><br></br>
<h:panelGrid columns="2" class="form-row" >

<h:outputText value="Budget" /> <h:inputText value="#{offersbean.budget}" class="form-control" />
<h:outputText value="Area" /> <h:inputText value="#{offersbean.area}" class="form-control" />

<h:outputText value="BUY/RENT"></h:outputText>
<h:selectOneMenu value="#{offersbean.typechval}">
<f:selectItem itemLabel="" itemValue=""/>
		<f:selectItems value="#{enumbean.typech}" />
</h:selectOneMenu>

				
<h:outputText value="Type"></h:outputText>
<h:selectOneMenu value="#{offersbean.typeval}">
<f:selectItem itemLabel="" itemValue=""/>
		<f:selectItems value="#{enumbean.type}"/>
</h:selectOneMenu>






<h:outputText value="Governorate"></h:outputText>

<h:selectOneMenu id="statesSelectUi" value="#{offersbean.governorateenumval}">
<f:selectItem itemLabel="--- Select governorate ---" itemValue=""/>
		<f:selectItems value="#{enumbean.governorateenum}" />

                <f:ajax render="selectedItem"  event="change"  execute="statesSelectUi"/>
        
		
</h:selectOneMenu>



<h:outputText value="Delegation"></h:outputText>

<h:selectOneMenu   id="selectedItem" value="#{offersbean.delegationval}">
<f:selectItem itemLabel="" itemValue="" />
		<f:selectItems  hidden="true" value="#{offersbean.delegations}" />         
    
		
</h:selectOneMenu>





<h:commandButton id="btn" value="Scan" action="#{offersbean.scan()}" class="btn btn-primary btn-sm" /> <h:message for="btn"/>

   <br></br><br></br><br></br><br></br>



</h:panelGrid>
</h:form>

   
   
   
   
       <h:graphicImage library="img" name="product-content-bg.jpg" />
   
   
	</ui:define> 
</ui:composition> 
 

dari-web/src/main/webapp/offers/Index.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core" 	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"        xmlns:p="http://primefaces.org/ui"
	  xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"	template="/template/template.xhtml">
	<ui:param name="page_name" value="Connexion" />
	<ui:define name="content">
	    <div class="container">
        <div class="row">
            <div class="col-lg-8 offset-lg-2">
                <div class="pd-hero-text">

                    <h2>WELCOME</h2>
                   
            <h:form>
			<h5>	<h:outputText	value=" #{loginBean.login}" /> </h5>
										<h5>	<h:outputText	value=" #{loginBean.role}" /> </h5>
				
				<h:commandButton value="Logout" action="#{loginBean.doLogout()}" class="btn btn-primary btn-sm" />
			</h:form>

                </div>
            </div>
        </div>

    </div>
    <h:graphicImage library="img" name="product-content-bg.jpg" />



 <div class="top-properties-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="properties-title">
                        <div class="section-title">
                            <span>Top Offers for you</span>
                            <h2>Top Offers</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="top-properties-carousel owl-carousel">
              
              
              <ui:repeat  id="list" var="requests"  value="#{offersbean.requestslist}">
              <tr>
								
   						
								
							 <div class="single-top-properties">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="stp-pic">
		<td>
   								<h:graphicImage height="100" width="100" rendered="#{requests.budget >= 1 and requests.budget le 70000 and requests.typeCh == 0}" library="img" name="buy1.jpg" />
   								<h:graphicImage height="100" width="100" rendered="#{requests.budget > 70000 and requests.budget le 300000 and requests.typeCh == 0}" library="img" name="buy2.jpg" />
   								<h:graphicImage height="100" width="100" rendered="#{requests.budget > 300000 and requests.typeCh == 0}" library="img" name="buy3.jpg" />
   								<h:graphicImage height="100" width="100" rendered="#{requests.budget >= 1 and requests.budget le 300 and requests.typeCh == 1}" library="img" name="rent1.jpg" />
   								<h:graphicImage height="100" width="100" rendered="#{requests.budget > 300  and requests.budget le 1000 and requests.typeCh == 1}" library="img" name="rent2.jpg" />
   								<h:graphicImage height="100" width="100" rendered="#{requests.budget > 1000 and requests.typeCh == 1}" library="img" name="rent3.jpg" />
   								</td>                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="stp-text">
                                <div class="s-text">
                                <h:outputText value="BUY"  rendered="#{requests.typeCh ==0}"/>
								<h:outputText value="RENT"  rendered="#{requests.typeCh ==1}"/>
                                
                                </div>
                                <h2><h:outputText value="#{requests.title}" /></h2>
                                <div class="room-price">
                                    <span>Budget :</span>
                                    <h4>$<h:outputText value="#{requests.budget}" /></h4>
                                </div>
                                <div class="properties-location"><i class="icon_pin"></i> <h:outputText value="#{requests.countryIso3}" /> , <h:outputText value="#{requests.regionCode}" /></div>
                                <p><h:outputText value="#{requests.description}" /></p>
                                <ul class="room-features">
                                    <li>
                                        <i class="fa fa-arrows"></i>
                                        <p><h:outputText value="#{requests.area}" /> (Metre)</p>
                                    </li>
                                    <li>
                                        <i class="fa fa-bed"></i>
                                        <p>							   	<h:outputText value="S+0" rendered="#{requests.type ==0}"/>
								<h:outputText value="S+1" rendered="#{requests.type ==1}"/>
								<h:outputText value="S+2" rendered="#{requests.type ==2}"/>
								<h:outputText value="S+3" rendered="#{requests.type ==3}"/>
								<h:outputText value="S+4" rendered="#{requests.type ==4}"/>
								<h:outputText value="S+Plus" rendered="#{requests.type ==5}"/>
								<h:outputText value="Villa" rendered="#{requests.type ==6}"/>
								<h:outputText value="Fond de commerce" rendered="#{requests.type ==7}"/>
								<h:outputText value="Terrain" rendered="#{requests.type ==8}"/>
								<h:outputText value="Local" rendered="#{requests.type ==9}"/></p>
                                    </li>
                               <li>
                                        <i class="fa fa-road"></i>
                                        <p><h:outputText value="#{requests.distance}" /> (KM)</p>
                                    </li>
                                          <li>
                                        <i class="fa fa-percent"></i>
                                        <p>Almost <h:outputText value="#{requests.per}" /></p>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>			
					
										
								</tr>
             
           </ui:repeat>
     
            </div>
        </div>
    </div>



       <h:graphicImage library="img" name="product-content-bg.jpg" />

   
	</ui:define> 
</ui:composition> 
 